# -*- coding: utf-8 -*-
"""Image Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15cIN3-avAf3q7vWLOrbtHVf47N7R66Os
"""

from google.colab import drive
drive.mount('/content/drive')

ls

cd /content/drive/MyDrive/dataset

ls

pwd

# importing imagedatagenerator library

from tensorflow.keras.preprocessing.image import ImageDataGenerator

"""# Image Data Agumentation"""

#Configuring image Data Generator Class
#Setting Parameter for Image Augmentation for training data

train_datagen=ImageDataGenerator(rescale=1./255,horizontal_flip=True,vertical_flip=True, zoom_range=0.2)

#Image Data Augmentation for testing data

test_datagen= ImageDataGenerator(rescale=1./255)

"""## Apply ImageDataGenerator Functionality To Train And Test Dataset """

#Performing data augmentation to train data

x_train = train_datagen.flow_from_directory('/content/drive/MyDrive/dataset/train_set', target_size = (64,64), batch_size = 5, color_mode = 'rgb', class_mode = 'categorical')

#performing data augmentation to test data

x_test = test_datagen.flow_from_directory('/content/drive/MyDrive/dataset/test_set', target_size = (64,64), batch_size = 5, color_mode = 'rgb', class_mode = 'categorical')